export const WITHINGS_MEASUREMENT_TYPES = {
  WEIGHT: 1,
  FAT_MASS_WEIGHT: 8,
  DIASTOLIC_BLOOD_PRESSURE: 9,
  SYSTOLIC_BLOOD_PRESSURE: 10,
  HEART_PULSE: 11,
  MUSCLE_MASS: 76,
  VO2_MAX: 123,
} as const;
